name: build

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: test
        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: build
        run: ./gradlew remapJar

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod_jar
          path: build/libs/
